import random, math
random.seed(20260821)
# Each doodle is authored inside a 0..100 local box, stroke-only, so one scale
# and one rotation places it anywhere on the tile.
D = {
"book": "M10,72 C30,58 44,58 50,66 C56,58 70,58 90,72 M50,66 L50,30 M10,72 L10,34 C30,20 44,22 50,30 C56,22 70,20 90,34 L90,72 M20,40 h18 M20,50 h16 M62,40 h18 M62,52 h15",
"pencil": "M22,86 L30,64 L74,16 C78,12 86,18 82,24 L38,72 Z M30,64 L38,72 M26,75 L34,82 M74,16 L82,24",
"abc": "M12,80 L12,24 L88,18 L88,74 Z M26,64 L34,40 L42,64 M29,56 h10 M50,64 v-22 h8 a6,6 0 0 1 0,11 h-8 M50,53 h9 a6,6 0 0 1 0,11 h-9 M82,46 a10,11 0 1 0 0,14",
"globe": "M50,20 a24,24 0 1 0 0.1,0 Z M26,44 h48 M50,20 c-12,10 -12,38 0,48 M50,20 c12,10 12,38 0,48 M50,68 v12 M38,88 h24 M42,80 h16",
"bulb": "M50,18 a20,20 0 0 1 12,36 c-3,3 -3,6 -3,9 h-18 c0,-3 0,-6 -3,-9 A20,20 0 0 1 50,18 Z M41,70 h18 M43,78 h14 M46,85 h8",
"note": "M40,74 a9,7 0 1 0 0.1,0 Z M49,74 V22 L78,14 V62 M78,62 a9,7 0 1 0 0.1,0 Z M49,36 L78,28",
"spark": "M50,16 L57,42 L82,50 L57,58 L50,84 L43,58 L18,50 L43,42 Z",
"cloud": "M22,66 a14,14 0 0 1 6,-26 a18,18 0 0 1 34,-4 a14,14 0 0 1 16,30 Z",
"rocket": "M50,14 c14,12 20,28 20,44 l-10,10 h-20 l-10,-10 c0,-16 6,-32 20,-44 Z M40,58 l-14,10 l6,-22 M60,58 l14,10 l-6,-22 M50,38 a6,6 0 1 0 0.1,0 Z M44,78 l6,12 l6,-12",
"cap": "M12,42 L50,26 L88,42 L50,58 Z M26,50 v16 c8,8 40,8 48,0 V50 M82,46 v20 M82,70 a3,3 0 1 0 0.1,0",
"glass": "M42,44 a20,20 0 1 0 0.1,0 Z M56,58 L82,84 M36,38 a12,12 0 0 1 10,-6",
"ball": "M50,20 a30,30 0 1 0 0.1,0 Z M50,20 L30,38 L38,64 h24 l8,-26 Z M30,38 L20,34 M70,38 L80,34 M38,64 L30,76 M62,64 L70,76 M50,20 v-6",
"leaf": "M20,80 C24,40 56,16 82,18 C84,44 62,78 22,78 M20,80 C36,66 54,52 76,26",
"heart": "M50,80 C22,60 18,40 30,30 C40,22 50,32 50,38 C50,32 60,22 70,30 C82,40 78,60 50,80 Z",
"spiral": "M50,50 m0,-4 a4,4 0 1 1 -4,4 a8,8 0 1 0 8,8 a14,14 0 1 1 -14,-14 a20,20 0 1 0 20,20 a26,26 0 1 1 -26,-26",
"sun": "M50,34 a16,16 0 1 0 0.1,0 Z M50,10 v10 M50,80 v10 M14,50 h10 M76,50 h10 M25,25 l7,7 M68,68 l7,7 M75,25 l-7,7 M32,68 l-7,7",
"plane": "M14,52 L86,18 L60,84 L48,60 Z M14,52 L48,60 M48,60 L86,18",
"ruler": "M14,62 a36,36 0 0 1 72,0 Z M28,62 v-8 M42,62 v-11 M56,62 v-11 M70,62 v-8",
"apple": "M50,30 c-16,-10 -30,4 -26,22 c3,14 14,26 26,26 c12,0 23,-12 26,-26 c4,-18 -10,-32 -26,-22 Z M50,30 v-12 M50,20 c8,-6 16,-4 18,2 c-6,6 -14,4 -18,-2 Z",
"clip": "M62,22 L34,54 a10,10 0 0 0 14,14 L74,40 a16,16 0 0 0 -22,-22 L28,44 a22,22 0 0 0 30,30",
"star5": "M50,18 L61,42 L86,44 L67,60 L73,84 L50,70 L27,84 L33,60 L14,44 L39,42 Z",
"tick": "M22,52 L42,72 L80,26",
}
KEYS = list(D)
TILE = 900
MARGIN = 160   # a doodle is duplicated across the seam when its centre is this close to an edge

def place():
    """Jittered grid so the field reads as scattered but never clumps or gaps."""
    out, cells = [], 6
    step = TILE / cells
    for gy in range(cells):
        for gx in range(cells):
            if random.random() < 0.05:      # a few deliberate breathing holes
                continue
            cx = gx * step + step / 2 + random.uniform(-step * 0.33, step * 0.33)
            cy = gy * step + step / 2 + random.uniform(-step * 0.33, step * 0.33)
            out.append((cx, cy, random.choice(KEYS),
                        random.uniform(-26, 26),
                        random.uniform(0.88, 1.34)))
    return out

def glyph(key, cx, cy, rot, scale, jitter):
    """One doodle. Drawn twice at a hair's offset — that doubled, slightly
    misregistered line is what reads as pencil rather than vector."""
    s = scale * 1.05
    t = f'translate({cx:.1f},{cy:.1f}) rotate({rot:.1f}) scale({s:.3f}) translate(-50,-50)'
    a = f'<g transform="{t}"><path d="{D[key]}"/>'
    b = f'<g transform="translate({jitter[0]:.2f},{jitter[1]:.2f}) rotate({jitter[2]:.2f},50,50)"><path d="{D[key]}" opacity=".55"/></g></g>'
    return a + b

parts = []
for cx, cy, key, rot, scale in place():
    j = (random.uniform(-.9, .9), random.uniform(-.9, .9), random.uniform(-.7, .7))
    offsets = [(0, 0)]
    if cx < MARGIN: offsets.append((TILE, 0))
    if cx > TILE - MARGIN: offsets.append((-TILE, 0))
    if cy < MARGIN: offsets.append((0, TILE))
    if cy > TILE - MARGIN: offsets.append((0, -TILE))
    # corners need the diagonal copy too, or the seam shows at the tile corners
    if len(offsets) == 3:
        offsets.append((offsets[1][0], offsets[2][1]))
    for ox, oy in offsets:
        parts.append(glyph(key, cx + ox, cy + oy, rot, scale, j))

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {TILE} {TILE}" width="{TILE}" height="{TILE}">
<!-- Seamless pencil-doodle field: school and learning objects, drawn as if in
     the margin of an exercise book. Every doodle whose centre sits within
     {MARGIN}px of an edge is repeated across the opposite seam, so the tile
     repeats with no visible grid. Generated by scratchpad/doodles.py. -->
<g fill="none" stroke="#2b3448" stroke-width="2.9" stroke-linecap="round" stroke-linejoin="round" opacity="0.85">
{chr(10).join(parts)}
</g>
</svg>'''
open("public/doodles.svg", "w").write(svg)
print("doodles:", len(parts), "paths |", round(len(svg)/1024, 1), "KB")
